### ISSUE TITLE
Authentication view typo error and UI fixes

### ISSUE THREAD

**Issue by Nitin-Singh18** [nitin-787/mynotes#118]

**Comment by Nitin-Singh18** [comment]
Hey @nitin-787, 
there are some typing and UI fixes in the authentication screen.
Can I work on it?

**Comment by nitin-787** [comment]
@Nitin-Singh18 can you give me brief about the issue?

**Comment by Nitin-Singh18** [comment]
The issues are:-
1. Typing error below the register text
2. Color of Hint texts on both screen are different. 
3. Some texts can be more bold 
4. Widget to navigate between both the screens are placed at different position, it would be good to place register screen's widget at the bottom same as the login screen. 
Etc..

**Comment by nitin-787** [comment]
@Nitin-Singh18 you can't consider these are issues, these are some minor mistakes, It happens during development, and about the 4th point that your addressing this is because currently this app don't have google auth in register view, it'll be fine if we just copy the code from login view to register view
